PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:  <http://awesom-minecraft-item-resolver.mc>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?stackSize ?description ?wikiUrl
WHERE {
  BIND(mc:lantern AS ?item)
  ?item rdf:label ?name . 
  ?item mc:stackSize ?stackSize . 
  ?item rdf:comment ?description . 
  ?item mc:wikiUrl ?wikiUrl .
  ?item rdf:type ?itemType . 
  ?itemType rdfs:subClassOf mc:Item
}