PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:  <http://minecraft-item-resolver.mc>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  {
    SELECT ?name ?stackSize ?description ?outputAmount ?recipeType 
    {
      BIND(mc:redstone_comparator AS ?item) . 
      ?item rdf:label ?name .  
      ?item mc:stackSize ?stackSize .
      ?item rdf:comment ?description .
      ?recipeType rdfs:subPropertyOf mc:recipe . 
      {
        ?item ?recipeType _:recipe .
        _:recipe mc:outputAmount ?outputAmount
      }
    }
  } UNION {
	SELECT ?name ?stackSize ?description ?slot
    {
      BIND(mc:redstone_comparator AS ?item) .
      {
        ?recipeType rdfs:subPropertyOf mc:recipe . 
        ?item ?recipeType _:recipe2 .
        _:recipe2 mc:recipeList _:list .
        _:list rdf:li _:element2 .
        _:element2 mc:receipeItem ?element .
        _:element2 mc:slot ?slot .
        ?element rdf:label ?name .
        ?element mc:stackSize ?stackSize .
        ?element rdf:comment ?description 
        
      }
    }
    ORDER BY ?slot
  }
}