PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:  <http://minecraft-item-resolver.mc>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  (COUNT(DISTINCT ?craftable) as ?count) 
WHERE {
  BIND(mc:stick AS ?item) .
  ?craftable ((mc:shapelessRecipe | mc:shapefulRecipe | mc:smeltingRecipe)/mc:recipeList/rdf:li/mc:recipeItem) ?item .
}