PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:  <http://awesom-minecraft-item-resolver.mc>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  ?ingriedient
WHERE {
  mc:bookshelf ((mc:shapelessRecipe | mc:shapefulRecipe | mc:smeltingRecipe)/rdf:li/mc:receipeItem)+ ?ingriedient .
  ?ingriedient rdf:type mc:CollectableItem .
}
