PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:  <http://awesom-minecraft-item-resolver.mc>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?stackSize ?description ?outputAmount ?recipeType ?ingredient ?slot ?ingredientDescription
WHERE {
  BIND(mc:lantern AS ?item) .
  ?item rdf:label ?name .  
  ?item mc:stackSize ?stackSize .
  ?item rdf:comment ?description 
  { 
    ?recipeType rdfs:subPropertyOf mc:recipe . 
    ?item ?recipeType _:recipe .
    _:recipe mc:outputAmount ?outputAmount . 
    _:recipe rdf:li _:element .
    _:element mc:slot ?slot .
    _:element mc:receipeItem ?element .
    ?element rdf:label ?ingredient .
    ?element rdf:comment ?ingredientDescription
  }
}
ORDER BY ?slot


# Getrennte Abfrage

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:  <http://awesom-minecraft-item-resolver.mc>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?stackSize ?description ?outputAmount ?recipeType
WHERE {
  BIND(mc:lantern AS ?item) .
  ?item rdf:label ?name .  
  ?item mc:stackSize ?stackSize .
  ?item rdf:comment ?description .
  ?item rdf:label ?ingredient .
  ?recipeType rdfs:subPropertyOf mc:recipe . 
  ?item ?recipeType _:recipe .
  _:recipe mc:outputAmount ?outputAmount
}

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:  <http://awesom-minecraft-item-resolver.mc>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?slot ?name ?description 
WHERE {
  BIND(mc:lantern AS ?item) .
  { 
    ?recipeType rdfs:subPropertyOf mc:recipe . 
    ?item ?recipeType _:recipe .
    _:recipe rdf:li _:element .
    _:element mc:receipeItem ?element .
    _:element mc:slot ?slot .
    ?element rdf:label ?name .  
    ?element rdf:comment ?description .
    ?element rdf:label ?ingredient
  }
}
ORDER BY ?slot
